Add fab for announcements
onc-healthit/site-ui-4 pull request #109
Opened 2024-08-08 20:00 UTC by mattystank

Includes
- Notification Panel
- Update content for Communication FAB ( due to other ticket on the board)
- Notification History page/timeline
- Notification Service to hold notifications

2024-08-12 20:51 UTC, drbgfc commented on src/assets/NotificationService.tsx
> +export const fetchMarkdownData = async () => {
This code looks familiar to somethign I wrote so I'm just wondering - are we duplicating it vs referencing it or did we just move it here?

2024-08-12 20:52 UTC, drbgfc commented on src/assets/NotificationService.tsx
> +export const fetchMarkdownData = async () => {
Basically, if we can externalize it to one function, or, at least, externalize the constants so they aren't defined 2x, that'd be best. Of course, I haven't verified that this wasn't just moved and everything references this now. So, just a note.

2024-08-12 20:53 UTC, drbgfc commented on src/assets/NotificationService.tsx
> +export const fetchMarkdownData = async () => {
Or that this is unique. I see it's really just some setters, so might be appropriate. And may even be the only place these constants are now

2024-08-12 21:00 UTC, drbgfc commented on src/assets/NotificationService.tsx
> +export const fetchMarkdownData = async () => {
OK, I see now that both CommunicationFab and Notifications use the release version and date so they both duplicate the same code essentially and have their own states for it. Instead, we should have that done in one location and imported into the two componenents. That way, they are synchronized, simplified, shared code, and it improves performance. I just intended a quick scan since Anusha is reviewing so feel free to correct me if I'm wrong.

2024-08-12 21:04 UTC, drbgfc commented on src/components/shared/notifications/NotificationsHistory.tsx
> +  const [loading, setLoading] = useState<boolean>(true) // TypeScript type for loading state
The comment prior makes sense, although maybe not needed, as Announcement looks like a custom type. However, the next two comments should be removed because the types are generic types so I'm not sure what the comment sare trying to imply?

2024-08-12 21:06 UTC, drbgfc reviewed
I just scanned it, so, we will wait for Anusha to do a real review, but, you knocked out a lot of work man, thanks!

2024-08-13 13:33 UTC, akanuri9 commented on src/assets/NotificationService.tsx
> +  const releaseVersionURL = 'https://raw.githubusercontent.com/onc-healthit/site-content/master/site-ui-4/version.md'
These can be moved to env variables and defined in .env file as there can used during build time. So, you dont have define them twice and just reference the variables.

2024-08-13 14:08 UTC, akanuri9 commented on src/assets/NotificationService.tsx
> +export const fetchMarkdownData = async () => {
I agree with Dan's comments, if we can call this code one time instead of duplicate that would be optimal. May be having a server component, make a call there and pass on the data to Communication and Notifications components so you avoid the multiple fetch calls. Just an idea!

2024-08-13 15:59 UTC, akanuri9 requested changes
added my comments, please review and make change to add env variables for the mentioned consts.

2024-08-19 21:35 UTC, akanuri9 approved these changes
looks good, thanks for making the changes.

2024-08-19 21:35 UTC, merged