feat: save and delete user testing profiles
onc-healthit/site-ui-4 pull request #147
Opened 2024-10-01 16:32 UTC by Plow74

2024-10-03 21:46 UTC, drbgfc commented on src/components/direct/shared/Profile.tsx
> +      const filteredProiles = removeProfilesWithNullProfileName(loggedInUsersProfiles)
Might want to fix typo: Proiles -> Profiles

2024-10-03 21:48 UTC, drbgfc commented on src/components/direct/shared/Profile.tsx
> +        const filteredProiles = removeProfilesWithNullProfileName(loggedInUsersProfiles)
same

2024-10-03 21:55 UTC, drbgfc requested changes
This is awesome, man, thanks so much! Glad to see the reusable approach.
This is reviewed/approved but I'd like the build issue addressed before merging.
I didn't notice it, but, if your using the shared custom switch with label, after you pull, there will be an error due to a fixed typo. So, just fix the import if that's the case.

Once addressed, feel free to Squash and merge into dev yourself.

2024-10-07 18:40 UTC, Plow74 commented on src/components/direct/shared/Profile.tsx
> +      const filteredProiles = removeProfilesWithNullProfileName(loggedInUsersProfiles)
fixed

2024-10-07 18:40 UTC, Plow74 commented on src/components/direct/shared/Profile.tsx
> +        const filteredProiles = removeProfilesWithNullProfileName(loggedInUsersProfiles)
fixed

2024-10-07 18:42 UTC, merged