Add Direct XDR Edge test tool functionality
onc-healthit/site-ui-4 pull request #148
Opened 2024-10-02 14:22 UTC by brooke-ritchey

2024-10-03 21:09 UTC, drbgfc commented on src/components/direct/xdr-edge/XDREdgeTestTool.tsx
> +export default async function XDREdgeTest() {
Making function components in React is not considered best practice. It can cause strange results in rendering as well as block the UI.
Something like this _should_ get around that concern (not tested):

```
export default function XDREdgeTest() {
  const [sampleCCDAFiles, setSampleCCDAFiles] = useState<string[]>([])
  const sampleCCDAFilesEndpoint = process.env.TTT_SAMPLE_CCDA_FILES_ENDPOINT || ''

  useEffect(() => {
    const fetchSampleFiles = async () => {
      const files = await getSampleCCDAFiles(sampleCCDAFilesEndpoint)
      setSampleCCDAFiles(files || [])
    }

    fetchSampleFiles()
  }, [sampleCCDAFilesEndpoint])

  return <XDREdgeTestContent sampleCCDAFiles={sampleCCDAFiles} />
}
```

2024-10-03 21:16 UTC, drbgfc commented on src/components/direct/xdr-edge/actions.ts
> +          error: 'They was an error connecting to the backend, Please try again later!',
There's a minor typo. But, since this is generic, for consistency, please use this instead:
src\constants\errorConstants.ts\GENERIC_ERROR_MESSAGE

2024-10-03 21:17 UTC, drbgfc commented on src/components/direct/xdr-edge/actions.ts
> +          error: 'They was an error connecting to the backend, Please try again later!',
Same, please use the constant instead in this case

2024-10-03 21:22 UTC, drbgfc commented on src/components/direct/xdr-edge/ValidateResult.tsx
> +const ReceiveMessageSITEResults = ({ response, buttonTitle }: ResultsComponentProps) => {
Should maybe the filename (ValidateResult) match the fucntion component name ReceiveMessageSITEResults? I suppose if you think it's clearer as is (and it very well may ne), then that's all good. I just don't often see that, so noted.

2024-10-03 21:30 UTC, drbgfc commented on src/components/direct/xdr-edge/send/SendForm.tsx
> +import SwitchWithLabel from '@components/shared/SwitchWIthLabel'
This typo has since been fixed. So, please pull the latest, expect a compile error, and update to @components/shared/SwitchWithLabel vs SwitchWIthLabel. Please ensure there are no other outdated imports in your code.

2024-10-03 21:35 UTC, drbgfc requested changes
That was a lot of great work, @brooke-ritchey, thanks! I listed just a few minor things to update. Some are optional.
@akanuri9 it might be good if you could breifly review as well if possible. But, all good if no time.

2024-10-04 16:24 UTC, drbgfc commented on src/components/direct/xdr-edge/XDREdgeTestTool.tsx
> +export default async function XDREdgeTest() {
Update:

For a fully client-side function (as most are), it would be problematic because React components expect to return JSX synchronously. 

*BUT, when rendering server-side, the async function can resolve before rendering begins, making it a clean solution.

So, no change needed, thanks!

2024-10-04 16:42 UTC, akanuri9 commented on src/components/direct/xdr-edge/XDREdgeTestTool.tsx
> +  const sampleCCDAFilesEndpoint = process.env.TTT_SAMPLE_CCDA_FILES_ENDPOINT || ''
i would suggest to add default endpoint of prod instead of ' ' to avoid any build error, because during build it wont find the variable which are not public and throw a error it shouldnt cause it to fail but a cleaner way.

2024-10-04 20:45 UTC, drbgfc commented on src/components/direct/xdr-edge/XDREdgeTestTool.tsx
> +  const sampleCCDAFilesEndpoint = process.env.TTT_SAMPLE_CCDA_FILES_ENDPOINT || ''
Thanks for reviewing, @akanuri9 !
I'm going to merge as is for now. I want to discuss this and we can decide if adding as part of another PR

2024-10-04 20:47 UTC, merged

2024-10-04 20:49 UTC, akanuri9 commented on src/components/direct/xdr-edge/XDREdgeTestTool.tsx
> +  const sampleCCDAFilesEndpoint = process.env.TTT_SAMPLE_CCDA_FILES_ENDPOINT || ''
It should be ok, we dont need to address now and it can be done later.