Fix scorecard Try Me not able to be used twice
onc-healthit/site-ui-4 pull request #232
Opened 2024-11-22 19:50 UTC by ebrockainq

2024-11-25 23:36 UTC, drbgfc commented on src/components/c-cda/scorecard/ScorecardHome.tsx
> +      setScorecardResponseJson({ ...newScorecardResponseJson })
Going to assume this spread wasn't enough to make it a unique/trigger a new component load?

2024-11-25 23:40 UTC, drbgfc commented on src/components/c-cda/scorecard/ScorecardHome.tsx
> +    resetResultsData()
This is a problem. As is, if we call resetResultsData() then it sets isTryMe to false which causes a button to appear which should not, among other possible side-effects. If you think it makes sense (and I can see the validity) then we need a boolean argument to be added to resetResultsData to set isTryMe as needed.

2024-11-25 23:45 UTC, drbgfc commented on src/components/c-cda/scorecard/ScorecardHome.tsx
> +  const [dialogKey, setDialogKey] = useState(0)
This is a perfectly fine solution. But, if it worke. something like this might be simpler as it's all contained in one place/requires no new state?   

```
  if (isValidResults) {
    setResultsDialogState(false); // Reset the state
    setTimeout(() => setResultsDialogState(true), 0); // Trigger the dialog
```

2024-11-25 23:46 UTC, drbgfc requested changes
Thanks for looking into this!
The comment about resetResultsData needs to be reviewed (the diff) and addressed

2024-11-26 16:38 UTC, ebrockainq commented on src/components/c-cda/scorecard/ScorecardHome.tsx
> +      setScorecardResponseJson({ ...newScorecardResponseJson })
Yes, that's correct, that's why it would only work again if the results actually changed, if you ran the same sample again, it would never show up

2024-11-26 17:13 UTC, ebrockainq commented on src/components/c-cda/scorecard/ScorecardHome.tsx
> +  const [dialogKey, setDialogKey] = useState(0)
That worked fine, so I removed the state I added

2024-11-26 20:03 UTC, drbgfc commented on src/components/c-cda/scorecard/ScorecardHome.tsx
> +    resetResultsData()
Oh ok, I missed that you reset it. But yeah, removing is best as that's the tested state. Thanks!

2024-11-26 20:07 UTC, drbgfc approved these changes

2024-11-26 20:07 UTC, drbgfc commented on src/components/c-cda/scorecard/ScorecardHome.tsx
> +  const [dialogKey, setDialogKey] = useState(0)
Cool!

2024-11-26 20:08 UTC, merged