Site 3986
onc-healthit/site-ui-4 pull request #67
Opened 2024-05-29 16:10 UTC by ebrockainq

2024-06-04 16:06 UTC, akanuri9 requested changes

2024-06-04 16:06 UTC, akanuri9 commented on src/components/direct/hisp/data/SMTPTestCases.tsx
> +      moreInfo: {
The content here in these files are more static content based of https://github.com/onc-healthit/ett/blob/f766d1f20ba56c4f1167f22a8df4bfafaff830bf/gui/src/assets/xdrtestCases.json and I think it should be considered as data file, I am note sure having imports into this file makes sense. Instead you can dynamically show the icons based on the data. I think it will be difficult for maintenance.

2024-06-04 19:09 UTC, ebrockainq commented on src/components/direct/hisp/TestCard.tsx
> -  longDesc?: string
That appears to be accidental, I will revert that

2024-06-04 19:10 UTC, ebrockainq commented on src/components/direct/hisp/TestCard.tsx
> -        {test.ccdaFileRequired && (
This was also a mistake, I will correct it

2024-06-04 19:10 UTC, ebrockainq commented on src/components/direct/hisp/data/SMTPTestCases.tsx
> +      moreInfo: {
I see what you mean, I'll try to find a solution to this

2024-06-06 15:26 UTC, akanuri9 approved these changes
Looks good, i believe this is going to change a bit when we get to functionality.

I see that the build check has failed, please correct the errors.

2024-06-07 14:56 UTC, merged